"""migration after first many-to-many User-Pub relationship solving attempt

Revision ID: 0e131309ad80
Revises: 6b5e5047ec32
Create Date: 2020-05-04 13:14:25.085284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e131309ad80'
down_revision = '6b5e5047ec32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('owners', 'lastSession',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.add_column('pubs', sa.Column('bookable', sa.Boolean(), nullable=False))
    op.drop_column('pubs', 'isBookable')
    op.add_column('reservations', sa.Column('at_id', sa.Integer(), nullable=True))
    op.add_column('reservations', sa.Column('by_id', sa.Integer(), nullable=True))
    op.add_column('reservations', sa.Column('guests', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_reservations_QR_code'), 'reservations', ['QR_code'], unique=False)
    op.create_foreign_key(None, 'reservations', 'pubs', ['at_id'], ['id'])
    op.create_foreign_key(None, 'reservations', 'users', ['by_id'], ['id'])
    op.drop_column('reservations', 'booked_by')
    op.drop_column('reservations', 'seats')
    op.drop_column('reservations', 'booked_at')
    op.alter_column('users', 'lastSession',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'lastSession',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.add_column('reservations', sa.Column('booked_at', sa.BOOLEAN(), nullable=True))
    op.add_column('reservations', sa.Column('seats', sa.INTEGER(), nullable=True))
    op.add_column('reservations', sa.Column('booked_by', sa.BOOLEAN(), nullable=True))
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_index(op.f('ix_reservations_QR_code'), table_name='reservations')
    op.drop_column('reservations', 'guests')
    op.drop_column('reservations', 'by_id')
    op.drop_column('reservations', 'at_id')
    op.add_column('pubs', sa.Column('isBookable', sa.BOOLEAN(), nullable=False))
    op.drop_column('pubs', 'bookable')
    op.alter_column('owners', 'lastSession',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
