"""26-06-2020 -- an intricate network

Revision ID: 2f327f1f6523
Revises: 933e39bfb63c
Create Date: 2020-06-30 18:43:17.505907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f327f1f6523'
down_revision = '933e39bfb63c'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('reservations', sa.Column('code', sa.Integer(), nullable=False))
	op.create_index(op.f('ix_reservations_code'), 'reservations', ['code'], unique=False)
	op.drop_index('ix_reservations_QR_code', table_name='reservations')
	op.drop_column('reservations', 'QR_code')
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('reservations', sa.Column('QR_code', sa.INTEGER(), nullable=False))
	op.create_index('ix_reservations_QR_code', 'reservations', ['QR_code'], unique=False)
	op.drop_index(op.f('ix_reservations_code'), table_name='reservations')
	op.drop_column('reservations', 'code')
	# ### end Alembic commands ###
