"""empty message

Revision ID: 41b27620cdab
Revises: 0e131309ad80
Create Date: 2020-05-04 17:02:05.880651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41b27620cdab'
down_revision = '0e131309ad80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('owners', 'subsExpirationDate',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('owners', 'subsExpirationDate',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
