"""init migration

Revision ID: 498070d65f61
Revises: 
Create Date: 2020-04-19 17:18:41.207605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498070d65f61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('administrator', sa.String(length=15), nullable=False),
    sa.Column('members', sa.Integer(), nullable=True),
    sa.Column('watchlist', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('administrator'),
    sa.UniqueConstraint('name')
    )
    op.create_table('local-partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('pswHash', sa.String(length=60), nullable=False),
    sa.Column('ownerFirstName', sa.String(), nullable=False),
    sa.Column('ownerLastName', sa.String(), nullable=False),
    sa.Column('businessAddress', sa.String(), nullable=False),
    sa.Column('isBookable', sa.Boolean(), nullable=False),
    sa.Column('seatsMax', sa.Integer(), nullable=False),
    sa.Column('seatsBooked', sa.Integer(), nullable=False),
    sa.Column('businessRating', sa.Integer(), nullable=False),
    sa.Column('subsType', sa.String(), nullable=False),
    sa.Column('subsExpirationDate', sa.DateTime(), nullable=True),
    sa.Column('businessDescription', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Binary(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('opponents', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('pswHash', sa.String(length=60), nullable=False),
    sa.Column('firstName', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('sports', sa.Integer(), nullable=True),
    sa.Column('groups', sa.Integer(), nullable=True),
    sa.Column('lastSession', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('matches')
    op.drop_table('local-partners')
    op.drop_table('group')
    # ### end Alembic commands ###
