"""empty message

Revision ID: 67d9438d6a3b
Revises: 2f327f1f6523
Create Date: 2020-07-13 01:25:13.423285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d9438d6a3b'
down_revision = '2f327f1f6523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pubs', sa.Column('name', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pubs', 'name')
    # ### end Alembic commands ###
