"""migration after first one-to-one relationship implementation

Revision ID: 6b5e5047ec32
Revises: 881cfa9d2a12
Create Date: 2020-05-03 20:30:16.785752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b5e5047ec32'
down_revision = '881cfa9d2a12'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('pubs', sa.Column('address', sa.String(), nullable=False))
	op.add_column('pubs', sa.Column('description', sa.Text(length=500), nullable=True))
	op.drop_column('pubs', 'businessDescription')
	op.drop_column('pubs', 'businessAddress')
	op.drop_column('pubs', 'ownerCredentials')
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('pubs', sa.Column('ownerCredentials', sa.BOOLEAN(), nullable=True))
	op.add_column('pubs', sa.Column('businessAddress', sa.VARCHAR(), nullable=False))
	op.add_column('pubs', sa.Column('businessDescription', sa.TEXT(), nullable=True))
	op.drop_column('pubs', 'description')
	op.drop_column('pubs', 'address')
	# ### end Alembic commands ###
