"""first migration under db restructuring

Revision ID: 881cfa9d2a12
Revises: 
Create Date: 2020-04-29 17:59:50.267897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881cfa9d2a12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('members', sa.Boolean(), nullable=True),
    sa.Column('watchlist', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('groups-subs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member', sa.Boolean(), nullable=True),
    sa.Column('group', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.String(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Binary(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('opponents', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('lastSession', sa.DateTime(), nullable=True),
    sa.Column('firstName', sa.String(length=60), nullable=False),
    sa.Column('lastName', sa.String(length=60), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('pswHash', sa.String(length=60), nullable=False),
    sa.Column('subsType', sa.String(), nullable=False),
    sa.Column('subsExpirationDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owners_email'), 'owners', ['email'], unique=True)
    op.create_index(op.f('ix_owners_username'), 'owners', ['username'], unique=True)
    op.create_table('reservations',
    sa.Column('QR_code', sa.String(), nullable=False),
    sa.Column('booked_by', sa.Boolean(), nullable=True),
    sa.Column('booked_at', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('QR_code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('lastSession', sa.DateTime(), nullable=True),
    sa.Column('firstName', sa.String(length=60), nullable=False),
    sa.Column('lastName', sa.String(length=60), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('pswHash', sa.String(length=60), nullable=False),
    sa.Column('sports', sa.Boolean(), nullable=True),
    sa.Column('groups', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('pubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('ownerCredentials', sa.Boolean(), nullable=True),
    sa.Column('businessAddress', sa.String(), nullable=False),
    sa.Column('isBookable', sa.Boolean(), nullable=False),
    sa.Column('seatsMax', sa.Integer(), nullable=False),
    sa.Column('seatsBooked', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('businessDescription', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pubs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_owners_username'), table_name='owners')
    op.drop_index(op.f('ix_owners_email'), table_name='owners')
    op.drop_table('owners')
    op.drop_table('matches')
    op.drop_table('groups-subs')
    op.drop_table('groups')
    # ### end Alembic commands ###
